### ISSUE TITLE
Credit show on display

### ISSUE THREAD

**Issue by isokdz** [LanguidSmartass/mdb-arduino-cashless#16]
Hello. Really really thank you. 
İs it possible to show credit on vendig  display. 
Credi 9.99 
Because item price expensive then 0. 
I couldnt vend any more.

**Comment by mkrasselt1** [comment]
what do you mean by show credit on display, if the vendining machine allowas access to its display you could answer the poll with a display request and the text as a payload.
otherwise the machine should display the kredit/money when you anser the poll with funds availiable (according to the mdb specifications)

**Comment by LanguidSmartass** [comment]
Closing the issue since is not directly connected with the example in this repository.
